name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    #- name: configure
      #run: ./configure
    - name: make
      run: make
    - name: make check
      run: |
        make check_hashmap
        echo Running test_hashmap...
        ./test_hashmap
        make check_queue
        echo Running test_queue...
        ./test_queue
        make check_thread_pool
        echo Running test_thread_pool...
        ./check_thread_pool
    #- name: make distcheck
    #  run: make distcheck
